### PR TITLE
Added brackets check, `from` constructor, and simplified execution

### PR DESCRIPTION
**Pull request by Princic-1837592**
Added the `from` function for when you want to initialize the `Machine` with a specified length for the `data_tape.`
Implemented a brackets check while parsing the file: now brackets are matched in pairs and an error is returned if some are mismatched.
Simplified adds and subs. Simplified jumping between brackets.
Now `parse_instructions` resets values to support multiple executions.

### CODE REVIEW

**Comment by chitramdasgupta** [comment]
Really great job! I reviewed your code and it runs twice as fast on `examples/mandelbrot.bf`!

I see you have made `data_tape` a `vec<u8>` and are initializing the `Machine` with `from(tape_length)` with the parameter `tape_length` for `data_tape`. Did you suppose to make `data_tape` initializable to an arbitrary specified length? If that is so, then in the present form there is no way to do so because `main()` calls `Machine::new()` which in turn calls `from(tape_length)` with `tape_length=TAPE_LEN`

**Comment by Princic-1837592** [comment]
Yes but you could think about extending the main to accept the length from command line. This could be useful when you want to run a program knowing that you won't use more than `x` cells, so it's useless to store `30_000` cells if `30_000>>x`.
Also next step in my opinion would be to convert a series of `>` instructions in a single instructions that jumps as many times as needed. This is the same for `<`, `+` and `-`. You can do this by adding a `(usize)` in the enum kind like i did with the brackets

**Comment by chitramdasgupta** [comment]
I don't think making `main()` take the *number of cells* is a good idea. How will the user who just wants to run their *Brainfuck* code know how many cells there will be in the `data_tape`?

Condensing multiple `+` or `>` into *one* instruction is a brilliant idea! I expect it would enhance the performance of the code greatly. Would you like to give it a go?

**Comment by Princic-1837592** [comment]
Let the user decide whether to input the number of cells or not. If not,
just use the default (30_000).

I will give a look at condensing instruction in a few hours. Maybe you can
do your own work on it on a different branch, and i'll do my own on another
branch. Then we can compare the two implementations and decide which one to
merge

Il mer 6 lug 2022, 11:22 Chitram Dasgupta ***@***.***> ha
scritto:

**Comment by chitramdasgupta** [comment]
Yeah, letting the user decide whether to input the *number of cells* is a good idea.

I am opening an `issue` on condensing the `>`, `<` and the like instructions.

**Comment by chitramdasgupta** [comment]
I will look into the condensing part as well :+1:

**Pull request merged**
